import type { CountryCode } from "@/lib/countries";
import type { Coordinates } from "@/lib/map-projection";

/**
 * One map pin per ISO 3166-1 country, for the public tracking route map.
 *
 * GENERATED by `scripts/generate-country-coordinates.ts` from Natural Earth's
 * `ne_10m_admin_0_countries` (PUBLIC DOMAIN) and committed, rather than
 * computed at runtime — the same arrangement as `lib/countries.ts`.
 *
 * These are Natural Earth's LABEL_X/LABEL_Y, which are hand-placed label
 * anchors, NOT computed centroids: the centroid of Indonesia falls in the Java
 * Sea and the centroid of Norway falls in Sweden. A handful of territories
 * Natural Earth folds into a parent are marked `hand-filled`.
 *
 * Client-safe: plain data, no dependencies.
 */
export const COUNTRY_COORDINATES: Record<CountryCode, Coordinates> = {
  AF: { lat: 34.2, lng: 66.5 },
  AX: { lat: 60.2, lng: 19.9 }, // hand-filled
  AL: { lat: 40.7, lng: 20.1 },
  DZ: { lat: 27.4, lng: 2.8 },
  AS: { lat: -14.3, lng: -170.7 },
  AD: { lat: 42.5, lng: 1.5 }, // hand-filled
  AO: { lat: -12.2, lng: 18 },
  AI: { lat: 18.2, lng: -63 },
  AQ: { lat: -79.8, lng: 35.9 }, // hand-filled
  AG: { lat: 17.4, lng: -61.8 },
  AR: { lat: -33.5, lng: -64.2 },
  AM: { lat: 40.5, lng: 44.8 },
  AW: { lat: 12.5, lng: -70 },
  AU: { lat: -24.1, lng: 134 },
  AT: { lat: 47.5, lng: 14.1 },
  AZ: { lat: 40.4, lng: 47.2 },
  BS: { lat: 26.4, lng: -77.1 },
  BH: { lat: 26.1, lng: 50.6 }, // hand-filled
  BD: { lat: 24.2, lng: 89.7 },
  BB: { lat: 13.2, lng: -59.6 },
  BY: { lat: 53.8, lng: 28.4 },
  BE: { lat: 50.8, lng: 4.8 },
  BZ: { lat: 17.2, lng: -88.7 },
  BJ: { lat: 10.3, lng: 2.4 },
  BM: { lat: 32.3, lng: -64.8 },
  BT: { lat: 27.5, lng: 90 },
  BO: { lat: -16.7, lng: -64.6 },
  BA: { lat: 44.1, lng: 18.1 },
  BW: { lat: -22.1, lng: 24.2 },
  BV: { lat: -54.4, lng: 3.4 }, // hand-filled
  BR: { lat: -12.1, lng: -49.6 },
  IO: { lat: -6.2, lng: 71.3 }, // hand-filled
  VG: { lat: 18.4, lng: -64.6 },
  BN: { lat: 4.4, lng: 114.6 },
  BG: { lat: 42.5, lng: 25.2 },
  BF: { lat: 12.7, lng: -1.4 },
  BI: { lat: -3.3, lng: 29.9 },
  KH: { lat: 12.6, lng: 104.5 },
  CM: { lat: 4.6, lng: 12.5 },
  CA: { lat: 60.3, lng: -101.9 },
  CV: { lat: 15.1, lng: -23.6 },
  BQ: { lat: 12.2, lng: -68.3 }, // hand-filled
  KY: { lat: 19.3, lng: -81.2 },
  CF: { lat: 7, lng: 20.9 },
  TD: { lat: 15.1, lng: 18.6 },
  CL: { lat: -38.2, lng: -72.3 },
  CN: { lat: 32.5, lng: 106.3 },
  CX: { lat: -10.5, lng: 105.6 }, // hand-filled
  CC: { lat: -12.2, lng: 96.9 }, // hand-filled
  CO: { lat: 3.4, lng: -73.2 },
  KM: { lat: -11.7, lng: 43.3 },
  CG: { lat: 0.1, lng: 15.9 },
  CD: { lat: -1.9, lng: 23.5 },
  CK: { lat: -21.2, lng: -159.8 },
  CR: { lat: 10.1, lng: -84.1 },
  CI: { lat: 7.5, lng: -5.6 },
  HR: { lat: 45.8, lng: 16.4 },
  CU: { lat: 21.3, lng: -78 },
  CW: { lat: 12.1, lng: -68.9 },
  CY: { lat: 34.9, lng: 33.1 },
  CZ: { lat: 49.9, lng: 15.4 },
  DK: { lat: 56, lng: 9 },
  DJ: { lat: 12, lng: 42.5 },
  DM: { lat: 15.5, lng: -61.3 },
  DO: { lat: 19.1, lng: -70.7 },
  EC: { lat: -1.3, lng: -78.2 },
  EG: { lat: 26.2, lng: 29.4 },
  SV: { lat: 13.7, lng: -88.9 },
  GQ: { lat: 2.3, lng: 9 },
  ER: { lat: 15.8, lng: 38.3 },
  EE: { lat: 58.7, lng: 25.9 },
  SZ: { lat: -26.5, lng: 31.5 },
  ET: { lat: 8, lng: 39.1 },
  FK: { lat: -51.6, lng: -58.7 },
  FO: { lat: 62.2, lng: -7.1 },
  FJ: { lat: -17.8, lng: 178 },
  FI: { lat: 63.3, lng: 27.3 },
  FR: { lat: 46.7, lng: 2.6 },
  GF: { lat: 4, lng: -53 }, // hand-filled
  PF: { lat: -17.6, lng: -149.5 },
  TF: { lat: -49.3, lng: 69.1 }, // hand-filled
  GA: { lat: -0.4, lng: 11.8 },
  GM: { lat: 13.6, lng: -15 },
  GE: { lat: 41.9, lng: 43.7 },
  DE: { lat: 51, lng: 9.7 },
  GH: { lat: 7.7, lng: -1 },
  GI: { lat: 36.1, lng: -5.3 }, // hand-filled
  GR: { lat: 39.5, lng: 21.7 },
  GL: { lat: 74.3, lng: -39.3 },
  GD: { lat: 12.1, lng: -61.7 },
  GP: { lat: 16.3, lng: -61.6 }, // hand-filled
  GU: { lat: 13.4, lng: 144.7 },
  GT: { lat: 15, lng: -90.5 },
  GG: { lat: 49.5, lng: -2.6 }, // hand-filled
  GN: { lat: 10.6, lng: -10 },
  GW: { lat: 12.2, lng: -14.5 },
  GY: { lat: 5.1, lng: -58.9 },
  HT: { lat: 19.3, lng: -72.2 },
  HM: { lat: -53.1, lng: 73.5 }, // hand-filled
  HN: { lat: 14.8, lng: -86.9 },
  HK: { lat: 22.4, lng: 114.1 }, // hand-filled
  HU: { lat: 47.1, lng: 19.4 },
  IS: { lat: 64.8, lng: -18.7 },
  IN: { lat: 22.7, lng: 79.4 },
  ID: { lat: -1, lng: 101.9 },
  IR: { lat: 32.2, lng: 54.9 },
  IQ: { lat: 33.1, lng: 43.3 },
  IE: { lat: 53.1, lng: -7.8 },
  IM: { lat: 54.2, lng: -4.5 }, // hand-filled
  IL: { lat: 30.9, lng: 34.8 },
  IT: { lat: 44.7, lng: 11.1 },
  JM: { lat: 18.1, lng: -77.3 },
  JP: { lat: 36.1, lng: 138.4 },
  JE: { lat: 49.2, lng: -2.1 }, // hand-filled
  JO: { lat: 30.8, lng: 36.4 },
  KZ: { lat: 49.1, lng: 68.7 },
  KE: { lat: 0.5, lng: 37.9 },
  KI: { lat: 1.8, lng: -157.4 },
  KW: { lat: 29.4, lng: 47.3 },
  KG: { lat: 41.7, lng: 74.5 },
  LA: { lat: 19.4, lng: 102.5 },
  LV: { lat: 57.1, lng: 25.5 },
  LB: { lat: 34.1, lng: 36 },
  LS: { lat: -29.5, lng: 28.2 },
  LR: { lat: 6.4, lng: -9.5 },
  LY: { lat: 26.6, lng: 18 },
  LI: { lat: 47.1, lng: 9.6 }, // hand-filled
  LT: { lat: 55.1, lng: 24.1 },
  LU: { lat: 49.7, lng: 6.1 },
  MO: { lat: 22.1, lng: 113.6 }, // hand-filled
  MG: { lat: -18.6, lng: 46.7 },
  MW: { lat: -13.4, lng: 33.6 },
  MY: { lat: 2.5, lng: 113.8 },
  MV: { lat: 4.2, lng: 73.5 }, // hand-filled
  ML: { lat: 18.7, lng: -2 },
  MT: { lat: 35.9, lng: 14.4 }, // hand-filled
  MH: { lat: 7.1, lng: 171.2 }, // hand-filled
  MQ: { lat: 14.6, lng: -61 }, // hand-filled
  MR: { lat: 19.6, lng: -9.7 },
  MU: { lat: -20.3, lng: 57.6 },
  YT: { lat: -12.8, lng: 45.2 }, // hand-filled
  MX: { lat: 23.9, lng: -102.3 },
  FM: { lat: 6.9, lng: 158.2 },
  MD: { lat: 47.4, lng: 28.5 },
  MC: { lat: 43.7, lng: 7.4 }, // hand-filled
  MN: { lat: 46, lng: 104.2 },
  ME: { lat: 42.8, lng: 19.1 },
  MS: { lat: 16.7, lng: -62.2 },
  MA: { lat: 31.7, lng: -7.2 },
  MZ: { lat: -13.9, lng: 37.8 },
  MM: { lat: 21.6, lng: 95.8 },
  NA: { lat: -20.6, lng: 17.1 },
  NR: { lat: -0.5, lng: 166.9 }, // hand-filled
  NP: { lat: 28.3, lng: 83.6 },
  NL: { lat: 52.4, lng: 5.6 },
  NC: { lat: -21.1, lng: 165.1 },
  NZ: { lat: -39.8, lng: 172.8 },
  NI: { lat: 12.7, lng: -85.1 },
  NE: { lat: 17.4, lng: 9.5 },
  NG: { lat: 9.4, lng: 7.5 },
  NU: { lat: -19, lng: -169.9 },
  NF: { lat: -29, lng: 168 }, // hand-filled
  KP: { lat: 39.9, lng: 126.4 },
  MK: { lat: 41.6, lng: 21.6 },
  MP: { lat: 15.2, lng: 145.7 },
  NO: { lat: 61.4, lng: 9.7 },
  OM: { lat: 22.1, lng: 57.3 },
  PK: { lat: 29.3, lng: 68.5 },
  PW: { lat: 7.5, lng: 134.6 }, // hand-filled
  PS: { lat: 32, lng: 35.3 },
  PA: { lat: 8.7, lng: -80.4 },
  PG: { lat: -5.7, lng: 143.9 },
  PY: { lat: -21.7, lng: -60.1 },
  PE: { lat: -13, lng: -72.9 },
  PH: { lat: 11.2, lng: 122.5 },
  PN: { lat: -24.4, lng: -128.3 }, // hand-filled
  PL: { lat: 52, lng: 19.5 },
  PT: { lat: 39.6, lng: -8.3 },
  PR: { lat: 18.2, lng: -66.5 },
  QA: { lat: 25.2, lng: 51.1 },
  RE: { lat: -21.1, lng: 55.5 }, // hand-filled
  RO: { lat: 45.7, lng: 25 },
  RU: { lat: 58.2, lng: 44.7 },
  RW: { lat: -1.9, lng: 30.1 },
  WS: { lat: -13.6, lng: -172.4 },
  SM: { lat: 43.9, lng: 12.4 }, // hand-filled
  ST: { lat: 1, lng: 7 },
  SA: { lat: 23.8, lng: 44.7 },
  SN: { lat: 15.1, lng: -14.8 },
  RS: { lat: 44.2, lng: 20.8 },
  SC: { lat: -4.7, lng: 55.5 },
  SL: { lat: 8.6, lng: -11.8 },
  SG: { lat: 1.4, lng: 103.8 }, // hand-filled
  SX: { lat: 18, lng: -63.1 }, // hand-filled
  SK: { lat: 48.7, lng: 19 },
  SI: { lat: 46.1, lng: 14.9 },
  SB: { lat: -8, lng: 159.2 },
  SO: { lat: 3.6, lng: 45.2 },
  ZA: { lat: -29.7, lng: 23.7 },
  GS: { lat: -55.7, lng: -31.1 }, // hand-filled
  KR: { lat: 36.4, lng: 128.1 },
  SS: { lat: 7.2, lng: 30.4 },
  ES: { lat: 40.1, lng: -3.5 },
  LK: { lat: 7.6, lng: 80.7 },
  BL: { lat: 17.9, lng: -62.8 }, // hand-filled
  SH: { lat: -16, lng: -5.7 },
  KN: { lat: 17.3, lng: -62.8 },
  LC: { lat: 13.9, lng: -61 },
  MF: { lat: 18.1, lng: -63 }, // hand-filled
  PM: { lat: 47, lng: -56.3 },
  VC: { lat: 13.1, lng: -61.3 },
  SD: { lat: 16.3, lng: 29.3 },
  SR: { lat: 4.1, lng: -55.9 },
  SJ: { lat: 78.2, lng: 16 }, // hand-filled
  SE: { lat: 65.9, lng: 19 },
  CH: { lat: 46.7, lng: 7.5 },
  SY: { lat: 35, lng: 38.3 },
  TW: { lat: 23.7, lng: 120.9 },
  TJ: { lat: 38.2, lng: 72.6 },
  TZ: { lat: -6.1, lng: 35 },
  TH: { lat: 15.5, lng: 101.1 },
  TL: { lat: -8.8, lng: 125.9 },
  TG: { lat: 8.8, lng: 1.1 },
  TK: { lat: -9.2, lng: -171.8 }, // hand-filled
  TO: { lat: -21.2, lng: -175.2 },
  TT: { lat: 11, lng: -60.9 },
  TN: { lat: 33.7, lng: 9 },
  TR: { lat: 39.3, lng: 34.5 },
  TM: { lat: 39.9, lng: 58.7 },
  TC: { lat: 21.8, lng: -71.8 },
  TV: { lat: -8.5, lng: 179.2 }, // hand-filled
  UM: { lat: 19.3, lng: 166.6 }, // hand-filled
  VI: { lat: 17.7, lng: -64.8 },
  UG: { lat: 2, lng: 32.9 },
  UA: { lat: 49.7, lng: 32.1 },
  AE: { lat: 23.5, lng: 54.5 },
  GB: { lat: 54.4, lng: -2.1 },
  US: { lat: 39.5, lng: -97.5 },
  UY: { lat: -33, lng: -56 },
  UZ: { lat: 41.7, lng: 64 },
  VU: { lat: -15.4, lng: 166.9 },
  VA: { lat: 41.9, lng: 12.5 }, // hand-filled
  VE: { lat: 7.2, lng: -64.6 },
  VN: { lat: 21.7, lng: 105.4 },
  WF: { lat: -14.3, lng: -178.1 },
  EH: { lat: 24, lng: -12.6 },
  YE: { lat: 15.3, lng: 45.9 },
  ZM: { lat: -14.7, lng: 26.4 },
  ZW: { lat: -18.9, lng: 29.9 },
};
