/**
 * Generates `public/brand/world-map.svg` — the backdrop for the public tracking
 * page's route map.
 *
 * Source: Natural Earth `ne_110m_land`, which is PUBLIC DOMAIN
 * (https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md —
 * "Everything here is public domain", no attribution required).
 *
 * The coastline is projected through the APPLICATION'S OWN
 * `src/lib/map-projection.ts`. That import is load-bearing: it is what makes the
 * committed SVG and the pins drawn over it share one coordinate system by
 * construction rather than by agreement. Change MAP_WIDTH/MAP_HEIGHT there and
 * this must be re-run.
 *
 * Run with: npm run map:world
 */
import { writeFileSync } from "node:fs";

import { MAP_HEIGHT, MAP_WIDTH, project } from "../src/lib/map-projection.ts";

const SOURCE =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_land.geojson";

const OUTPUT = "public/brand/world-map.svg";

/** Douglas–Peucker tolerance in degrees. The knob for output size. */
const EPSILON = 0.25;

/** Rings smaller than this in degrees render as sub-pixel specks. */
const MIN_EXTENT = 0.6;

/** A 15° graticule, matching the decorative grid on suez-canal-map.svg. */
const GRATICULE = MAP_WIDTH / 24;

type Position = [number, number];

/** Perpendicular distance from `point` to the segment `start`–`end`. */
function perpendicularDistance(point: Position, start: Position, end: Position): number {
  const dx = end[0] - start[0];
  const dy = end[1] - start[1];

  if (dx === 0 && dy === 0) return Math.hypot(point[0] - start[0], point[1] - start[1]);

  // |cross product| / |segment|, the standard point-to-line distance.
  const cross = Math.abs(dy * point[0] - dx * point[1] + end[0] * start[1] - end[1] * start[0]);
  return cross / Math.hypot(dx, dy);
}

/**
 * Douglas–Peucker, iteratively rather than recursively: a few of these rings run
 * to thousands of points and a naive recursion can blow the stack.
 */
function simplify(points: readonly Position[], epsilon: number): Position[] {
  if (points.length < 3) return [...points];

  const keep = new Array<boolean>(points.length).fill(false);
  keep[0] = true;
  keep[points.length - 1] = true;

  const stack: [number, number][] = [[0, points.length - 1]];

  while (stack.length > 0) {
    const [first, last] = stack.pop()!;
    let furthest = -1;
    let maxDistance = epsilon;

    for (let i = first + 1; i < last; i += 1) {
      const distance = perpendicularDistance(points[i]!, points[first]!, points[last]!);
      if (distance > maxDistance) {
        maxDistance = distance;
        furthest = i;
      }
    }

    if (furthest !== -1) {
      keep[furthest] = true;
      stack.push([first, furthest], [furthest, last]);
    }
  }

  return points.filter((_, index) => keep[index]);
}

function extent(ring: readonly Position[]): number {
  const lngs = ring.map((p) => p[0]);
  const lats = ring.map((p) => p[1]);
  return Math.max(Math.max(...lngs) - Math.min(...lngs), Math.max(...lats) - Math.min(...lats));
}

const round = (value: number): string => (Math.round(value * 10) / 10).toString();

function ringToPath(ring: readonly Position[]): string {
  const projected = ring.map(([lng, lat]) => project({ lat, lng }));
  const [first, ...rest] = projected;
  if (!first) return "";

  return (
    `M${round(first.x)} ${round(first.y)}` +
    rest.map((point) => `L${round(point.x)} ${round(point.y)}`).join("") +
    "Z"
  );
}

type Geometry =
  | { type: "Polygon"; coordinates: Position[][] }
  | { type: "MultiPolygon"; coordinates: Position[][][] };

function ringsOf(geometry: Geometry): Position[][] {
  return geometry.type === "Polygon" ? geometry.coordinates : geometry.coordinates.flat();
}

async function main(): Promise<void> {
  console.log(`Fetching ${SOURCE}`);

  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`Source returned ${String(response.status)}`);

  const geojson = (await response.json()) as { features: { geometry: Geometry }[] };

  let kept = 0;
  let dropped = 0;
  let pointsBefore = 0;
  let pointsAfter = 0;

  const paths: string[] = [];

  for (const feature of geojson.features) {
    for (const ring of ringsOf(feature.geometry)) {
      if (extent(ring) < MIN_EXTENT) {
        dropped += 1;
        continue;
      }

      const simplified = simplify(ring, EPSILON);
      // Fewer than 3 points is not a shape.
      if (simplified.length < 3) {
        dropped += 1;
        continue;
      }

      pointsBefore += ring.length;
      pointsAfter += simplified.length;
      kept += 1;
      paths.push(ringToPath(simplified));
    }
  }

  // One path with evenodd, so a ring inside another ring renders as a hole
  // (inland seas) rather than painting over it.
  const svg = `<!-- GENERATED by scripts/generate-world-map.ts. Do not hand-edit; re-run instead.
     Coastline: Natural Earth ne_110m_land, public domain, simplified at ${String(EPSILON)}deg
     and projected through src/lib/map-projection.ts so the pins drawn over this
     map share its coordinate system by construction. Palette matches
     suez-canal-map.svg. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${String(MAP_WIDTH)}" height="${String(MAP_HEIGHT)}" viewBox="0 0 ${String(MAP_WIDTH)} ${String(MAP_HEIGHT)}">
  <defs>
    <pattern id="graticule" width="${round(GRATICULE)}" height="${round(GRATICULE)}" patternUnits="userSpaceOnUse">
      <path d="M${round(GRATICULE)} 0H0V${round(GRATICULE)}" fill="none" stroke="#f8e138" stroke-width="0.5"/>
    </pattern>
  </defs>
  <rect width="${String(MAP_WIDTH)}" height="${String(MAP_HEIGHT)}" fill="#0d1252"/>
  <rect width="${String(MAP_WIDTH)}" height="${String(MAP_HEIGHT)}" fill="url(#graticule)" opacity="0.1"/>
  <path d="${paths.join("")}" fill="#1b2456" fill-rule="evenodd"/>
</svg>
`;

  writeFileSync(OUTPUT, svg);

  const bytes = Buffer.byteLength(svg);
  console.log(
    `\nRings kept ${String(kept)}, dropped ${String(dropped)} (under ${String(MIN_EXTENT)}deg)`,
  );
  console.log(`Points ${String(pointsBefore)} -> ${String(pointsAfter)}`);
  console.log(`Wrote ${OUTPUT} — ${String(Math.round(bytes / 1024))} KB`);
  if (bytes > 60 * 1024) console.warn("Over the 60 KB budget: raise EPSILON and re-run.");
}

await main();
